version: '2'
services:
  backendtraining-postgresql:
    image: postgres:11.6
    # volumes:
    #     - ~/volumes/jhipster/backendtraining/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=backendtraining
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
